### PR TITLE
Add a dotnet compiler plugin

### PR DESCRIPTION
**Pull request by dkearns**

### CODE REVIEW

**Comment by nickspoons** [comment]
Thanks a lot @dkearns, I'd been meaning to do this for ages.

Trying it out locally, I'm getting duplicate errors in my quickfix results. This appears to be because of the "summary" that is output and can be suppressed with the "/clp:NoSummary" flag. I generally also suppress other unnecessary output to simplify errorformat parsing, so we could do this:

```
CompilerSet makeprg=dotnet\ build\ /nologo\ /clp:ErrorsOnly\ /clp:NoSummary
```

Here is a comparison of these commands on the command line:
```
$ dotnet build
Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  testing -> /data/code/test/unittests/testing/bin/Debug/net6.0/testing.dll
  nUnitTests -> /data/code/test/unittests/nUnitTests/bin/Debug/net6.0/nUnitTests.dll
/data/code/test/unittests/xUnitTests/UnitTest1.cs(10,17): error CS0117: 'Assert' does not contain a definition for 'otEqual' [/data/code/test/unittests/xUnitTests/Tests.csproj]

Build FAILED.

/data/code/test/unittests/xUnitTests/UnitTest1.cs(10,17): error CS0117: 'Assert' does not contain a definition for 'otEqual' [/data/code/test/unittests/xUnitTests/Tests.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.26
```

```
$ dotnet build /nologo /clp:ErrorsOnly /clp:NoSummary
/data/code/test/unittests/xUnitTests/UnitTest1.cs(10,17): error CS0117: 'Assert' does not contain a definition for 'otEqual' [/data/code/test/unittests/xUnitTests/Tests.csproj]
```

---

Also, as a personal preference, I am not interested in seeing the project name output next to every error - I can deduce that from the file location. However some people will appreciate seeing it (it's part of the error output after all). Do you think a feature flag to suppress it is a good idea, or is that a bit fiddly? After all, if users can add a variable to suppress the project name, they can presumably also override the errorformat.

This is what I'm thinking about:

```vim
if get(g:, 'dotnet_suppress_project_name', v:false)
  CompilerSet errorformat=%E%f(%l\\,%c):\ %trror\ CS%n:\ %m [%*\\S],
                         \%W%f(%l\\,%c):\ %tarning\ CS%n:\ %m [%*\\S],
                         \%-G%.%#
else
  CompilerSet errorformat=%E%f(%l\\,%c):\ %trror\ CS%n:\ %m,
                         \%W%f(%l\\,%c):\ %tarning\ CS%n:\ %m,
                         \%-G%.%#
endif
```
What do you think?

**Comment by dkearns** [comment]
`-nologo` and `-clp:nosummary` look good to me but `-clp:errorsonly` seems like it should be configurable.

Every time I make `makeprg` too opinionated users complain and unfortunately the same users prefer options rather than overriding `makeprg` and `errorformat`.  So I don't see a problem with adding a few options.

It's a bit odd that you can't disable showing the project file with `noshowprojectfile` in error messages.

As there's multiple error message number prefixes, e.g. NETSDKXXXX, should we just include that in the error message rather than matching it with `%n`?

**Comment by nickspoons** [comment]
You might be right about `-clp:errorsonly`, and in fact in might be better to leave it out completely.

> As there's multiple error message number prefixes, e.g. NETSDKXXXX, should we just include that in the error message rather than matching it with %n?

That is a good idea, I don't know that the `%n` is very useful without the prefix.

**Comment by nickspoons** [comment]
Nice! Thanks @dkearns

**Pull request merged**
